//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.34014
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 
namespace TesteXMI1 {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="org.omg.xmi.namespace.UML", IsNullable=false)]
    public partial class Model {
        
        private ModelNamespaceownedElement namespaceownedElementField;
        
        private ModelTaggedValue[] modelElementtaggedValueField;
        
        private string nameField;
        
        private string xmiidField;
        
        private bool isRootField;
        
        private bool isLeafField;
        
        private bool isAbstractField;
        
        private bool isSpecificationField;
        
        private string visibilityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Namespace.ownedElement")]
        public ModelNamespaceownedElement NamespaceownedElement {
            get {
                return this.namespaceownedElementField;
            }
            set {
                this.namespaceownedElementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("ModelElement.taggedValue")]
        [System.Xml.Serialization.XmlArrayItemAttribute("TaggedValue", IsNullable=false)]
        public ModelTaggedValue[] ModelElementtaggedValue {
            get {
                return this.modelElementtaggedValueField;
            }
            set {
                this.modelElementtaggedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isRoot {
            get {
                return this.isRootField;
            }
            set {
                this.isRootField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isLeaf {
            get {
                return this.isLeafField;
            }
            set {
                this.isLeafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isAbstract {
            get {
                return this.isAbstractField;
            }
            set {
                this.isAbstractField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSpecification {
            get {
                return this.isSpecificationField;
            }
            set {
                this.isSpecificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElement {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Class", typeof(ModelNamespaceownedElementClass))]
        [System.Xml.Serialization.XmlElementAttribute("Collaboration", typeof(ModelNamespaceownedElementCollaboration))]
        [System.Xml.Serialization.XmlElementAttribute("TagDefinition", typeof(ModelNamespaceownedElementTagDefinition))]
        public object[] Items {
            get {
                return this.itemsField;
            }
            set {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementClass {
        
        private ModelNamespaceownedElementClassTaggedValue[] modelElementtaggedValueField;
        
        private string nameField;
        
        private string xmiidField;
        
        private string visibilityField;
        
        private bool isSpecificationField;
        
        private bool isRootField;
        
        private bool isLeafField;
        
        private bool isAbstractField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("ModelElement.taggedValue")]
        [System.Xml.Serialization.XmlArrayItemAttribute("TaggedValue", IsNullable=false)]
        public ModelNamespaceownedElementClassTaggedValue[] ModelElementtaggedValue {
            get {
                return this.modelElementtaggedValueField;
            }
            set {
                this.modelElementtaggedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSpecification {
            get {
                return this.isSpecificationField;
            }
            set {
                this.isSpecificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isRoot {
            get {
                return this.isRootField;
            }
            set {
                this.isRootField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isLeaf {
            get {
                return this.isLeafField;
            }
            set {
                this.isLeafField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isAbstract {
            get {
                return this.isAbstractField;
            }
            set {
                this.isAbstractField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementClassTaggedValue {
        
        private string taggedValuedataValueField;
        
        private ModelNamespaceownedElementClassTaggedValueTaggedValuetype taggedValuetypeField;
        
        private string xmiidField;
        
        private bool isSpecificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaggedValue.dataValue")]
        public string TaggedValuedataValue {
            get {
                return this.taggedValuedataValueField;
            }
            set {
                this.taggedValuedataValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaggedValue.type")]
        public ModelNamespaceownedElementClassTaggedValueTaggedValuetype TaggedValuetype {
            get {
                return this.taggedValuetypeField;
            }
            set {
                this.taggedValuetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSpecification {
            get {
                return this.isSpecificationField;
            }
            set {
                this.isSpecificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementClassTaggedValueTaggedValuetype {
        
        private ModelNamespaceownedElementClassTaggedValueTaggedValuetypeTagDefinition tagDefinitionField;
        
        /// <remarks/>
        public ModelNamespaceownedElementClassTaggedValueTaggedValuetypeTagDefinition TagDefinition {
            get {
                return this.tagDefinitionField;
            }
            set {
                this.tagDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementClassTaggedValueTaggedValuetypeTagDefinition {
        
        private string xmiidrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.idref")]
        public string xmiidref {
            get {
                return this.xmiidrefField;
            }
            set {
                this.xmiidrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaboration {
        
        private ModelNamespaceownedElementCollaborationClassifierRole[] namespaceownedElementField;
        
        private ModelNamespaceownedElementCollaborationCollaborationinteraction collaborationinteractionField;
        
        private string xmiidField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("Namespace.ownedElement")]
        [System.Xml.Serialization.XmlArrayItemAttribute("ClassifierRole", IsNullable=false)]
        public ModelNamespaceownedElementCollaborationClassifierRole[] NamespaceownedElement {
            get {
                return this.namespaceownedElementField;
            }
            set {
                this.namespaceownedElementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Collaboration.interaction")]
        public ModelNamespaceownedElementCollaborationCollaborationinteraction Collaborationinteraction {
            get {
                return this.collaborationinteractionField;
            }
            set {
                this.collaborationinteractionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaborationClassifierRole {
        
        private ModelNamespaceownedElementCollaborationClassifierRoleTaggedValue[] modelElementtaggedValueField;
        
        private string nameField;
        
        private string xmiidField;
        
        private string visibilityField;
        
        private bool isSpecificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("ModelElement.taggedValue")]
        [System.Xml.Serialization.XmlArrayItemAttribute("TaggedValue", IsNullable=false)]
        public ModelNamespaceownedElementCollaborationClassifierRoleTaggedValue[] ModelElementtaggedValue {
            get {
                return this.modelElementtaggedValueField;
            }
            set {
                this.modelElementtaggedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSpecification {
            get {
                return this.isSpecificationField;
            }
            set {
                this.isSpecificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaborationClassifierRoleTaggedValue {
        
        private string taggedValuedataValueField;
        
        private ModelNamespaceownedElementCollaborationClassifierRoleTaggedValueTaggedValuetype taggedValuetypeField;
        
        private string xmiidField;
        
        private bool isSpecificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaggedValue.dataValue")]
        public string TaggedValuedataValue {
            get {
                return this.taggedValuedataValueField;
            }
            set {
                this.taggedValuedataValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaggedValue.type")]
        public ModelNamespaceownedElementCollaborationClassifierRoleTaggedValueTaggedValuetype TaggedValuetype {
            get {
                return this.taggedValuetypeField;
            }
            set {
                this.taggedValuetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSpecification {
            get {
                return this.isSpecificationField;
            }
            set {
                this.isSpecificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaborationClassifierRoleTaggedValueTaggedValuetype {
        
        private ModelNamespaceownedElementCollaborationClassifierRoleTaggedValueTaggedValuetypeTagDefinition tagDefinitionField;
        
        /// <remarks/>
        public ModelNamespaceownedElementCollaborationClassifierRoleTaggedValueTaggedValuetypeTagDefinition TagDefinition {
            get {
                return this.tagDefinitionField;
            }
            set {
                this.tagDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaborationClassifierRoleTaggedValueTaggedValuetypeTagDefinition {
        
        private string xmiidrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.idref")]
        public string xmiidref {
            get {
                return this.xmiidrefField;
            }
            set {
                this.xmiidrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaborationCollaborationinteraction {
        
        private ModelNamespaceownedElementCollaborationCollaborationinteractionInteraction interactionField;
        
        /// <remarks/>
        public ModelNamespaceownedElementCollaborationCollaborationinteractionInteraction Interaction {
            get {
                return this.interactionField;
            }
            set {
                this.interactionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaborationCollaborationinteractionInteraction {
        
        private ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessage[] interactionmessageField;
        
        private string xmiidField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("Interaction.message")]
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
        public ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessage[] Interactionmessage {
            get {
                return this.interactionmessageField;
            }
            set {
                this.interactionmessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessage {
        
        private ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessageTaggedValue[] modelElementtaggedValueField;
        
        private string nameField;
        
        private string xmiidField;
        
        private string visibilityField;
        
        private string senderField;
        
        private string receiverField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("ModelElement.taggedValue")]
        [System.Xml.Serialization.XmlArrayItemAttribute("TaggedValue", IsNullable=false)]
        public ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessageTaggedValue[] ModelElementtaggedValue {
            get {
                return this.modelElementtaggedValueField;
            }
            set {
                this.modelElementtaggedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string visibility {
            get {
                return this.visibilityField;
            }
            set {
                this.visibilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string sender {
            get {
                return this.senderField;
            }
            set {
                this.senderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string receiver {
            get {
                return this.receiverField;
            }
            set {
                this.receiverField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessageTaggedValue {
        
        private string taggedValuedataValueField;
        
        private ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessageTaggedValueTaggedValuetype taggedValuetypeField;
        
        private string xmiidField;
        
        private bool isSpecificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaggedValue.dataValue")]
        public string TaggedValuedataValue {
            get {
                return this.taggedValuedataValueField;
            }
            set {
                this.taggedValuedataValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaggedValue.type")]
        public ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessageTaggedValueTaggedValuetype TaggedValuetype {
            get {
                return this.taggedValuetypeField;
            }
            set {
                this.taggedValuetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSpecification {
            get {
                return this.isSpecificationField;
            }
            set {
                this.isSpecificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessageTaggedValueTaggedValuetype {
        
        private ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessageTaggedValueTaggedValuetypeTagDefinition tagDefinitionField;
        
        /// <remarks/>
        public ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessageTaggedValueTaggedValuetypeTagDefinition TagDefinition {
            get {
                return this.tagDefinitionField;
            }
            set {
                this.tagDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementCollaborationCollaborationinteractionInteractionMessageTaggedValueTaggedValuetypeTagDefinition {
        
        private string xmiidrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.idref")]
        public string xmiidref {
            get {
                return this.xmiidrefField;
            }
            set {
                this.xmiidrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelNamespaceownedElementTagDefinition {
        
        private string xmiidField;
        
        private string nameField;
        
        private bool isSpecificationField;
        
        private string tagTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSpecification {
            get {
                return this.isSpecificationField;
            }
            set {
                this.isSpecificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string tagType {
            get {
                return this.tagTypeField;
            }
            set {
                this.tagTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelTaggedValue {
        
        private string taggedValuedataValueField;
        
        private ModelTaggedValueTaggedValuetype taggedValuetypeField;
        
        private string xmiidField;
        
        private bool isSpecificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaggedValue.dataValue")]
        public string TaggedValuedataValue {
            get {
                return this.taggedValuedataValueField;
            }
            set {
                this.taggedValuedataValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaggedValue.type")]
        public ModelTaggedValueTaggedValuetype TaggedValuetype {
            get {
                return this.taggedValuetypeField;
            }
            set {
                this.taggedValuetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSpecification {
            get {
                return this.isSpecificationField;
            }
            set {
                this.isSpecificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelTaggedValueTaggedValuetype {
        
        private ModelTaggedValueTaggedValuetypeTagDefinition tagDefinitionField;
        
        /// <remarks/>
        public ModelTaggedValueTaggedValuetypeTagDefinition TagDefinition {
            get {
                return this.tagDefinitionField;
            }
            set {
                this.tagDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class ModelTaggedValueTaggedValuetypeTagDefinition {
        
        private string xmiidrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.idref")]
        public string xmiidref {
            get {
                return this.xmiidrefField;
            }
            set {
                this.xmiidrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="org.omg.xmi.namespace.UML", IsNullable=false)]
    public partial class Diagram {
        
        private DiagramTaggedValue[] modelElementtaggedValueField;
        
        private DiagramDiagramElement[] diagramelementField;
        
        private string nameField;
        
        private string xmiidField;
        
        private string diagramTypeField;
        
        private string ownerField;
        
        private string toolNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("ModelElement.taggedValue")]
        [System.Xml.Serialization.XmlArrayItemAttribute("TaggedValue", IsNullable=false)]
        public DiagramTaggedValue[] ModelElementtaggedValue {
            get {
                return this.modelElementtaggedValueField;
            }
            set {
                this.modelElementtaggedValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("Diagram.element")]
        [System.Xml.Serialization.XmlArrayItemAttribute("DiagramElement", IsNullable=false)]
        public DiagramDiagramElement[] Diagramelement {
            get {
                return this.diagramelementField;
            }
            set {
                this.diagramelementField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string diagramType {
            get {
                return this.diagramTypeField;
            }
            set {
                this.diagramTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string toolName {
            get {
                return this.toolNameField;
            }
            set {
                this.toolNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class DiagramTaggedValue {
        
        private string taggedValuedataValueField;
        
        private DiagramTaggedValueTaggedValuetype taggedValuetypeField;
        
        private string xmiidField;
        
        private bool isSpecificationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaggedValue.dataValue")]
        public string TaggedValuedataValue {
            get {
                return this.taggedValuedataValueField;
            }
            set {
                this.taggedValuedataValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("TaggedValue.type")]
        public DiagramTaggedValueTaggedValuetype TaggedValuetype {
            get {
                return this.taggedValuetypeField;
            }
            set {
                this.taggedValuetypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.id")]
        public string xmiid {
            get {
                return this.xmiidField;
            }
            set {
                this.xmiidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool isSpecification {
            get {
                return this.isSpecificationField;
            }
            set {
                this.isSpecificationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class DiagramTaggedValueTaggedValuetype {
        
        private DiagramTaggedValueTaggedValuetypeTagDefinition tagDefinitionField;
        
        /// <remarks/>
        public DiagramTaggedValueTaggedValuetypeTagDefinition TagDefinition {
            get {
                return this.tagDefinitionField;
            }
            set {
                this.tagDefinitionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class DiagramTaggedValueTaggedValuetypeTagDefinition {
        
        private string xmiidrefField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("xmi.idref")]
        public string xmiidref {
            get {
                return this.xmiidrefField;
            }
            set {
                this.xmiidrefField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="org.omg.xmi.namespace.UML")]
    public partial class DiagramDiagramElement {
        
        private string geometryField;
        
        private string subjectField;
        
        private byte seqnoField;
        
        private bool seqnoFieldSpecified;
        
        private string styleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string geometry {
            get {
                return this.geometryField;
            }
            set {
                this.geometryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public byte seqno {
            get {
                return this.seqnoField;
            }
            set {
                this.seqnoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool seqnoSpecified {
            get {
                return this.seqnoFieldSpecified;
            }
            set {
                this.seqnoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string style {
            get {
                return this.styleField;
            }
            set {
                this.styleField = value;
            }
        }
    }
}
